/**
 * Country codes with flags for phone number inputs
 * Shared across authentication and guest bidder forms
 */

export interface CountryCode {
  id: string;
  code: string;
  country: string;
  flag: string;
}

export const COUNTRY_CODES: CountryCode[] = [
  // Popular countries (top of list)
  { id: 'AE', code: '+971', country: 'UAE', flag: '🇦🇪' },
  { id: 'US', code: '+1', country: 'USA', flag: '🇺🇸' },
  { id: 'GB', code: '+44', country: 'UK', flag: '🇬🇧' },
  { id: 'IN', code: '+91', country: 'India', flag: '🇮🇳' },
  { id: 'SA', code: '+966', country: 'Saudi Arabia', flag: '🇸🇦' },
  { id: 'EG', code: '+20', country: 'Egypt', flag: '🇪🇬' },
  // All countries A-Z
  { id: 'AF', code: '+93', country: 'Afghanistan', flag: '🇦🇫' },
  { id: 'AL', code: '+355', country: 'Albania', flag: '🇦🇱' },
  { id: 'DZ', code: '+213', country: 'Algeria', flag: '🇩🇿' },
  { id: 'AS', code: '+1684', country: 'American Samoa', flag: '🇦🇸' },
  { id: 'AD', code: '+376', country: 'Andorra', flag: '🇦🇩' },
  { id: 'AO', code: '+244', country: 'Angola', flag: '🇦🇴' },
  { id: 'AI', code: '+1264', country: 'Anguilla', flag: '🇦🇮' },
  { id: 'AG', code: '+1268', country: 'Antigua and Barbuda', flag: '🇦🇬' },
  { id: 'AR', code: '+54', country: 'Argentina', flag: '🇦🇷' },
  { id: 'AM', code: '+374', country: 'Armenia', flag: '🇦🇲' },
  { id: 'AW', code: '+297', country: 'Aruba', flag: '🇦🇼' },
  { id: 'AU', code: '+61', country: 'Australia', flag: '🇦🇺' },
  { id: 'AT', code: '+43', country: 'Austria', flag: '🇦🇹' },
  { id: 'AZ', code: '+994', country: 'Azerbaijan', flag: '🇦🇿' },
  { id: 'BS', code: '+1242', country: 'Bahamas', flag: '🇧🇸' },
  { id: 'BH', code: '+973', country: 'Bahrain', flag: '🇧🇭' },
  { id: 'BD', code: '+880', country: 'Bangladesh', flag: '🇧🇩' },
  { id: 'BB', code: '+1246', country: 'Barbados', flag: '🇧🇧' },
  { id: 'BY', code: '+375', country: 'Belarus', flag: '🇧🇾' },
  { id: 'BE', code: '+32', country: 'Belgium', flag: '🇧🇪' },
  { id: 'BZ', code: '+501', country: 'Belize', flag: '🇧🇿' },
  { id: 'BJ', code: '+229', country: 'Benin', flag: '🇧🇯' },
  { id: 'BM', code: '+1441', country: 'Bermuda', flag: '🇧🇲' },
  { id: 'BT', code: '+975', country: 'Bhutan', flag: '🇧🇹' },
  { id: 'BO', code: '+591', country: 'Bolivia', flag: '🇧🇴' },
  { id: 'BA', code: '+387', country: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { id: 'BW', code: '+267', country: 'Botswana', flag: '🇧🇼' },
  { id: 'BR', code: '+55', country: 'Brazil', flag: '🇧🇷' },
  { id: 'BN', code: '+673', country: 'Brunei', flag: '🇧🇳' },
  { id: 'BG', code: '+359', country: 'Bulgaria', flag: '🇧🇬' },
  { id: 'BF', code: '+226', country: 'Burkina Faso', flag: '🇧🇫' },
  { id: 'BI', code: '+257', country: 'Burundi', flag: '🇧🇮' },
  { id: 'KH', code: '+855', country: 'Cambodia', flag: '🇰🇭' },
  { id: 'CM', code: '+237', country: 'Cameroon', flag: '🇨🇲' },
  { id: 'CA', code: '+1', country: 'Canada', flag: '🇨🇦' },
  { id: 'CV', code: '+238', country: 'Cape Verde', flag: '🇨🇻' },
  { id: 'KY', code: '+1345', country: 'Cayman Islands', flag: '🇰🇾' },
  { id: 'CF', code: '+236', country: 'Central African Republic', flag: '🇨🇫' },
  { id: 'TD', code: '+235', country: 'Chad', flag: '🇹🇩' },
  { id: 'CL', code: '+56', country: 'Chile', flag: '🇨🇱' },
  { id: 'CN', code: '+86', country: 'China', flag: '🇨🇳' },
  { id: 'CO', code: '+57', country: 'Colombia', flag: '🇨🇴' },
  { id: 'KM', code: '+269', country: 'Comoros', flag: '🇰🇲' },
  { id: 'CG', code: '+242', country: 'Congo', flag: '🇨🇬' },
  { id: 'CD', code: '+243', country: 'Congo (DRC)', flag: '🇨🇩' },
  { id: 'CK', code: '+682', country: 'Cook Islands', flag: '🇨🇰' },
  { id: 'CR', code: '+506', country: 'Costa Rica', flag: '🇨🇷' },
  { id: 'CI', code: '+225', country: 'Côte d\'Ivoire', flag: '🇨🇮' },
  { id: 'HR', code: '+385', country: 'Croatia', flag: '🇭🇷' },
  { id: 'CU', code: '+53', country: 'Cuba', flag: '🇨🇺' },
  { id: 'CY', code: '+357', country: 'Cyprus', flag: '🇨🇾' },
  { id: 'CZ', code: '+420', country: 'Czech Republic', flag: '🇨🇿' },
  { id: 'DK', code: '+45', country: 'Denmark', flag: '🇩🇰' },
  { id: 'DJ', code: '+253', country: 'Djibouti', flag: '🇩🇯' },
  { id: 'DM', code: '+1767', country: 'Dominica', flag: '🇩🇲' },
  { id: 'DO', code: '+1809', country: 'Dominican Republic', flag: '🇩🇴' },
  { id: 'EC', code: '+593', country: 'Ecuador', flag: '🇪🇨' },
  { id: 'SV', code: '+503', country: 'El Salvador', flag: '🇸🇻' },
  { id: 'GQ', code: '+240', country: 'Equatorial Guinea', flag: '🇬🇶' },
  { id: 'ER', code: '+291', country: 'Eritrea', flag: '🇪🇷' },
  { id: 'EE', code: '+372', country: 'Estonia', flag: '🇪🇪' },
  { id: 'ET', code: '+251', country: 'Ethiopia', flag: '🇪🇹' },
  { id: 'FK', code: '+500', country: 'Falkland Islands', flag: '🇫🇰' },
  { id: 'FO', code: '+298', country: 'Faroe Islands', flag: '🇫🇴' },
  { id: 'FJ', code: '+679', country: 'Fiji', flag: '🇫🇯' },
  { id: 'FI', code: '+358', country: 'Finland', flag: '🇫🇮' },
  { id: 'FR', code: '+33', country: 'France', flag: '🇫🇷' },
  { id: 'GF', code: '+594', country: 'French Guiana', flag: '🇬🇫' },
  { id: 'PF', code: '+689', country: 'French Polynesia', flag: '🇵🇫' },
  { id: 'GA', code: '+241', country: 'Gabon', flag: '🇬🇦' },
  { id: 'GM', code: '+220', country: 'Gambia', flag: '🇬🇲' },
  { id: 'GE', code: '+995', country: 'Georgia', flag: '🇬🇪' },
  { id: 'DE', code: '+49', country: 'Germany', flag: '🇩🇪' },
  { id: 'GH', code: '+233', country: 'Ghana', flag: '🇬🇭' },
  { id: 'GI', code: '+350', country: 'Gibraltar', flag: '🇬🇮' },
  { id: 'GR', code: '+30', country: 'Greece', flag: '🇬🇷' },
  { id: 'GL', code: '+299', country: 'Greenland', flag: '🇬🇱' },
  { id: 'GD', code: '+1473', country: 'Grenada', flag: '🇬🇩' },
  { id: 'GP', code: '+590', country: 'Guadeloupe', flag: '🇬🇵' },
  { id: 'GU', code: '+1671', country: 'Guam', flag: '🇬🇺' },
  { id: 'GT', code: '+502', country: 'Guatemala', flag: '🇬🇹' },
  { id: 'GN', code: '+224', country: 'Guinea', flag: '🇬🇳' },
  { id: 'GW', code: '+245', country: 'Guinea-Bissau', flag: '🇬🇼' },
  { id: 'GY', code: '+592', country: 'Guyana', flag: '🇬🇾' },
  { id: 'HT', code: '+509', country: 'Haiti', flag: '🇭🇹' },
  { id: 'HN', code: '+504', country: 'Honduras', flag: '🇭🇳' },
  { id: 'HK', code: '+852', country: 'Hong Kong', flag: '🇭🇰' },
  { id: 'HU', code: '+36', country: 'Hungary', flag: '🇭🇺' },
  { id: 'IS', code: '+354', country: 'Iceland', flag: '🇮🇸' },
  { id: 'ID', code: '+62', country: 'Indonesia', flag: '🇮🇩' },
  { id: 'IR', code: '+98', country: 'Iran', flag: '🇮🇷' },
  { id: 'IQ', code: '+964', country: 'Iraq', flag: '🇮🇶' },
  { id: 'IE', code: '+353', country: 'Ireland', flag: '🇮🇪' },
  { id: 'IL', code: '+972', country: 'Israel', flag: '🇮🇱' },
  { id: 'IT', code: '+39', country: 'Italy', flag: '🇮🇹' },
  { id: 'JM', code: '+1876', country: 'Jamaica', flag: '🇯🇲' },
  { id: 'JP', code: '+81', country: 'Japan', flag: '🇯🇵' },
  { id: 'JO', code: '+962', country: 'Jordan', flag: '🇯🇴' },
  { id: 'KZ', code: '+7', country: 'Kazakhstan', flag: '🇰🇿' },
  { id: 'KE', code: '+254', country: 'Kenya', flag: '🇰🇪' },
  { id: 'KI', code: '+686', country: 'Kiribati', flag: '🇰🇮' },
  { id: 'XK', code: '+383', country: 'Kosovo', flag: '🇽🇰' },
  { id: 'KW', code: '+965', country: 'Kuwait', flag: '🇰🇼' },
  { id: 'KG', code: '+996', country: 'Kyrgyzstan', flag: '🇰🇬' },
  { id: 'LA', code: '+856', country: 'Laos', flag: '🇱🇦' },
  { id: 'LV', code: '+371', country: 'Latvia', flag: '🇱🇻' },
  { id: 'LB', code: '+961', country: 'Lebanon', flag: '🇱🇧' },
  { id: 'LS', code: '+266', country: 'Lesotho', flag: '🇱🇸' },
  { id: 'LR', code: '+231', country: 'Liberia', flag: '🇱🇷' },
  { id: 'LY', code: '+218', country: 'Libya', flag: '🇱🇾' },
  { id: 'LI', code: '+423', country: 'Liechtenstein', flag: '🇱🇮' },
  { id: 'LT', code: '+370', country: 'Lithuania', flag: '🇱🇹' },
  { id: 'LU', code: '+352', country: 'Luxembourg', flag: '🇱🇺' },
  { id: 'MO', code: '+853', country: 'Macau', flag: '🇲🇴' },
  { id: 'MK', code: '+389', country: 'Macedonia', flag: '🇲🇰' },
  { id: 'MG', code: '+261', country: 'Madagascar', flag: '🇲🇬' },
  { id: 'MW', code: '+265', country: 'Malawi', flag: '🇲🇼' },
  { id: 'MY', code: '+60', country: 'Malaysia', flag: '🇲🇾' },
  { id: 'MV', code: '+960', country: 'Maldives', flag: '🇲🇻' },
  { id: 'ML', code: '+223', country: 'Mali', flag: '🇲🇱' },
  { id: 'MT', code: '+356', country: 'Malta', flag: '🇲🇹' },
  { id: 'MH', code: '+692', country: 'Marshall Islands', flag: '🇲🇭' },
  { id: 'MQ', code: '+596', country: 'Martinique', flag: '🇲🇶' },
  { id: 'MR', code: '+222', country: 'Mauritania', flag: '🇲🇷' },
  { id: 'MU', code: '+230', country: 'Mauritius', flag: '🇲🇺' },
  { id: 'YT', code: '+262', country: 'Mayotte', flag: '🇾🇹' },
  { id: 'MX', code: '+52', country: 'Mexico', flag: '🇲🇽' },
  { id: 'FM', code: '+691', country: 'Micronesia', flag: '🇫🇲' },
  { id: 'MD', code: '+373', country: 'Moldova', flag: '🇲🇩' },
  { id: 'MC', code: '+377', country: 'Monaco', flag: '🇲🇨' },
  { id: 'MN', code: '+976', country: 'Mongolia', flag: '🇲🇳' },
  { id: 'ME', code: '+382', country: 'Montenegro', flag: '🇲🇪' },
  { id: 'MS', code: '+1664', country: 'Montserrat', flag: '🇲🇸' },
  { id: 'MA', code: '+212', country: 'Morocco', flag: '🇲🇦' },
  { id: 'MZ', code: '+258', country: 'Mozambique', flag: '🇲🇿' },
  { id: 'MM', code: '+95', country: 'Myanmar', flag: '🇲🇲' },
  { id: 'NA', code: '+264', country: 'Namibia', flag: '🇳🇦' },
  { id: 'NR', code: '+674', country: 'Nauru', flag: '🇳🇷' },
  { id: 'NP', code: '+977', country: 'Nepal', flag: '🇳🇵' },
  { id: 'NL', code: '+31', country: 'Netherlands', flag: '🇳🇱' },
  { id: 'NC', code: '+687', country: 'New Caledonia', flag: '🇳🇨' },
  { id: 'NZ', code: '+64', country: 'New Zealand', flag: '🇳🇿' },
  { id: 'NI', code: '+505', country: 'Nicaragua', flag: '🇳🇮' },
  { id: 'NE', code: '+227', country: 'Niger', flag: '🇳🇪' },
  { id: 'NG', code: '+234', country: 'Nigeria', flag: '🇳🇬' },
  { id: 'NU', code: '+683', country: 'Niue', flag: '🇳🇺' },
  { id: 'KP', code: '+850', country: 'North Korea', flag: '🇰🇵' },
  { id: 'NO', code: '+47', country: 'Norway', flag: '🇳🇴' },
  { id: 'OM', code: '+968', country: 'Oman', flag: '🇴🇲' },
  { id: 'PK', code: '+92', country: 'Pakistan', flag: '🇵🇰' },
  { id: 'PW', code: '+680', country: 'Palau', flag: '🇵🇼' },
  { id: 'PS', code: '+970', country: 'Palestine', flag: '🇵🇸' },
  { id: 'PA', code: '+507', country: 'Panama', flag: '🇵🇦' },
  { id: 'PG', code: '+675', country: 'Papua New Guinea', flag: '🇵🇬' },
  { id: 'PY', code: '+595', country: 'Paraguay', flag: '🇵🇾' },
  { id: 'PE', code: '+51', country: 'Peru', flag: '🇵🇪' },
  { id: 'PH', code: '+63', country: 'Philippines', flag: '🇵🇭' },
  { id: 'PL', code: '+48', country: 'Poland', flag: '🇵🇱' },
  { id: 'PT', code: '+351', country: 'Portugal', flag: '🇵🇹' },
  { id: 'PR', code: '+1787', country: 'Puerto Rico', flag: '🇵🇷' },
  { id: 'QA', code: '+974', country: 'Qatar', flag: '🇶🇦' },
  { id: 'RE', code: '+262', country: 'Réunion', flag: '🇷🇪' },
  { id: 'RO', code: '+40', country: 'Romania', flag: '🇷🇴' },
  { id: 'RU', code: '+7', country: 'Russia', flag: '🇷🇺' },
  { id: 'RW', code: '+250', country: 'Rwanda', flag: '🇷🇼' },
  { id: 'SH', code: '+290', country: 'Saint Helena', flag: '🇸🇭' },
  { id: 'KN', code: '+1869', country: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { id: 'LC', code: '+1758', country: 'Saint Lucia', flag: '🇱🇨' },
  { id: 'PM', code: '+508', country: 'Saint Pierre and Miquelon', flag: '🇵🇲' },
  { id: 'VC', code: '+1784', country: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { id: 'WS', code: '+685', country: 'Samoa', flag: '🇼🇸' },
  { id: 'SM', code: '+378', country: 'San Marino', flag: '🇸🇲' },
  { id: 'ST', code: '+239', country: 'São Tomé and Príncipe', flag: '🇸🇹' },
  { id: 'SN', code: '+221', country: 'Senegal', flag: '🇸🇳' },
  { id: 'RS', code: '+381', country: 'Serbia', flag: '🇷🇸' },
  { id: 'SC', code: '+248', country: 'Seychelles', flag: '🇸🇨' },
  { id: 'SL', code: '+232', country: 'Sierra Leone', flag: '🇸🇱' },
  { id: 'SG', code: '+65', country: 'Singapore', flag: '🇸🇬' },
  { id: 'SK', code: '+421', country: 'Slovakia', flag: '🇸🇰' },
  { id: 'SI', code: '+386', country: 'Slovenia', flag: '🇸🇮' },
  { id: 'SB', code: '+677', country: 'Solomon Islands', flag: '🇸🇧' },
  { id: 'SO', code: '+252', country: 'Somalia', flag: '🇸🇴' },
  { id: 'ZA', code: '+27', country: 'South Africa', flag: '🇿🇦' },
  { id: 'KR', code: '+82', country: 'South Korea', flag: '🇰🇷' },
  { id: 'SS', code: '+211', country: 'South Sudan', flag: '🇸🇸' },
  { id: 'ES', code: '+34', country: 'Spain', flag: '🇪🇸' },
  { id: 'LK', code: '+94', country: 'Sri Lanka', flag: '🇱🇰' },
  { id: 'SD', code: '+249', country: 'Sudan', flag: '🇸🇩' },
  { id: 'SR', code: '+597', country: 'Suriname', flag: '🇸🇷' },
  { id: 'SZ', code: '+268', country: 'Swaziland', flag: '🇸🇿' },
  { id: 'SE', code: '+46', country: 'Sweden', flag: '🇸🇪' },
  { id: 'CH', code: '+41', country: 'Switzerland', flag: '🇨🇭' },
  { id: 'SY', code: '+963', country: 'Syria', flag: '🇸🇾' },
  { id: 'TW', code: '+886', country: 'Taiwan', flag: '🇹🇼' },
  { id: 'TJ', code: '+992', country: 'Tajikistan', flag: '🇹🇯' },
  { id: 'TZ', code: '+255', country: 'Tanzania', flag: '🇹🇿' },
  { id: 'TH', code: '+66', country: 'Thailand', flag: '🇹🇭' },
  { id: 'TL', code: '+670', country: 'Timor-Leste', flag: '🇹🇱' },
  { id: 'TG', code: '+228', country: 'Togo', flag: '🇹🇬' },
  { id: 'TK', code: '+690', country: 'Tokelau', flag: '🇹🇰' },
  { id: 'TO', code: '+676', country: 'Tonga', flag: '🇹🇴' },
  { id: 'TT', code: '+1868', country: 'Trinidad and Tobago', flag: '🇹🇹' },
  { id: 'TN', code: '+216', country: 'Tunisia', flag: '🇹🇳' },
  { id: 'TR', code: '+90', country: 'Turkey', flag: '🇹🇷' },
  { id: 'TM', code: '+993', country: 'Turkmenistan', flag: '🇹🇲' },
  { id: 'TC', code: '+1649', country: 'Turks and Caicos Islands', flag: '🇹🇨' },
  { id: 'TV', code: '+688', country: 'Tuvalu', flag: '🇹🇻' },
  { id: 'UG', code: '+256', country: 'Uganda', flag: '🇺🇬' },
  { id: 'UA', code: '+380', country: 'Ukraine', flag: '🇺🇦' },
  { id: 'UY', code: '+598', country: 'Uruguay', flag: '🇺🇾' },
  { id: 'UZ', code: '+998', country: 'Uzbekistan', flag: '🇺🇿' },
  { id: 'VU', code: '+678', country: 'Vanuatu', flag: '🇻🇺' },
  { id: 'VA', code: '+379', country: 'Vatican City', flag: '🇻🇦' },
  { id: 'VE', code: '+58', country: 'Venezuela', flag: '🇻🇪' },
  { id: 'VN', code: '+84', country: 'Vietnam', flag: '🇻🇳' },
  { id: 'VG', code: '+1284', country: 'Virgin Islands (British)', flag: '🇻🇬' },
  { id: 'VI', code: '+1340', country: 'Virgin Islands (US)', flag: '🇻🇮' },
  { id: 'WF', code: '+681', country: 'Wallis and Futuna', flag: '🇼🇫' },
  { id: 'YE', code: '+967', country: 'Yemen', flag: '🇾🇪' },
  { id: 'ZM', code: '+260', country: 'Zambia', flag: '🇿🇲' },
  { id: 'ZW', code: '+263', country: 'Zimbabwe', flag: '🇿🇼' },
];

// Helper to find country by dial code (returns first match - use for simple lookups)
export function findCountryByCode(dialCode: string): CountryCode | undefined {
  return COUNTRY_CODES.find(c => c.code === dialCode);
}

// Helper to find country by ID (unique)
export function findCountryById(id: string): CountryCode | undefined {
  return COUNTRY_CODES.find(c => c.id === id);
}

// Get all countries sorted alphabetically (excluding duplicates from popular section)
export function getAllCountriesSorted(): CountryCode[] {
  const seen = new Set<string>();
  return COUNTRY_CODES
    .filter(c => {
      if (seen.has(c.id)) return false;
      seen.add(c.id);
      return true;
    })
    .sort((a, b) => a.country.localeCompare(b.country));
}
