/**
 * Server-only city → country (display name) lookup.
 *
 * Data source: lib/cities/data.json — generated by scripts/build-cities-data.ts
 * from GeoNames cities15000 (CC-BY 4.0; attribution in README.md). Top 5000
 * cities by population, keyed by lowercase city name + asciiname → ISO-2.
 *
 * ISO-2 → display name translation uses lib/country-codes.ts (the same
 * canonical 228-entry list the phone pickers consume). DB stores display
 * names in `model_professionals.country` (free text), so the API response
 * returns the display name directly — no client-side translation needed.
 *
 * NEVER import this module from a client component or any 'use client'
 * boundary. Importing data.json into a client bundle would ship ~150-300
 * KB of geographic data to every page. Server-side usage only —
 * app/api/ambassador/lookup-country/route.ts is the sole consumer.
 */

import citiesData from '@/lib/cities/data.json'
import { COUNTRY_CODES } from '@/lib/country-codes'

const ISO_TO_DISPLAY: Map<string, string> = new Map(
  COUNTRY_CODES.map((c) => [c.id, c.country]),
)

const CITIES: Record<string, string> = citiesData as Record<string, string>

export function lookupCountryByCity(city: string): string | null {
  const key = city.trim().toLowerCase()
  if (!key) return null
  const iso2 = CITIES[key]
  if (!iso2) return null
  return ISO_TO_DISPLAY.get(iso2) ?? null
}
